import json

notebook = {
    "cells": [
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"id": "setup_cell"},
            "outputs": [],
            "source": [
                "# @title \ud83d\udee0\ufe0f 1. Setup & Authenticate JDownloader2\n",
                "# @markdown Installs dependencies, loads config, and boots JD2 in the background.\n",
                "ENV_FILE_PATH = \"/content/drive/MyDrive/config.txt\" # @param {type:\"string\"}\n",
                "\n",
                "import os\n",
                "import sys\n",
                "import subprocess\n",
                "import random\n",
                "import json\n",
                "import time\n",
                "\n",
                "if ENV_FILE_PATH.startswith(\"/content/drive\"):\n",
                "    print(\"[*] Mounting Google Drive to access config file...\")\n",
                "    from google.colab import drive\n",
                "    drive.mount('/content/drive')\n",
                "\n",
                "print(\"[*] Installing necessary dependencies...\")\n",
                "subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"pyrogram\", \"TgCrypto\", \"python-dotenv\", \"nest_asyncio\", \"aiohttp\"])\n",
                "subprocess.run([\"apt-get\", \"update\", \"-qq\"])\n",
                "subprocess.run([\"apt-get\", \"install\", \"-qq\", \"-y\", \"aria2\", \"default-jre-headless\", \"ffmpeg\"])\n",
                "\n",
                "from dotenv import load_dotenv\n",
                "if os.path.exists(ENV_FILE_PATH):\n",
                "    load_dotenv(ENV_FILE_PATH)\n",
                "    print(f\"[*] Loaded config file from {ENV_FILE_PATH}\")\n",
                "else:\n",
                "    print(f\"[!] No config file found at {ENV_FILE_PATH}. Make sure the path is correct!\")\n",
                "\n",
                "JD_EMAIL = os.environ.get(\"JD_EMAIL\")\n",
                "JD_PASS = os.environ.get(\"JD_PASS\")\n",
                "JD_FOLDER = \"/content/JDownloader\"\n",
                "os.makedirs(JD_FOLDER, exist_ok=True)\n",
                "\n",
                "if JD_EMAIL and JD_PASS:\n",
                "    if not os.path.exists(f\"{JD_FOLDER}/JDownloader.jar\"):\n",
                "        subprocess.run([\"wget\", \"-q\", \"-O\", f\"{JD_FOLDER}/JDownloader.jar\", \"http://installer.jdownloader.org/JDownloader.jar\"])\n",
                "    \n",
                "    cfg_dir = os.path.join(JD_FOLDER, \"cfg\")\n",
                "    os.makedirs(cfg_dir, exist_ok=True)\n",
                "    device_name = f\"Colab_Bot_{random.randint(100, 999)}\"\n",
                "    \n",
                "    jdata = {\"autoconnectenabledv2\": True, \"password\": JD_PASS, \"devicename\": device_name, \"email\": JD_EMAIL}\n",
                "    with open(os.path.join(cfg_dir, \"org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json\"), \"w\") as f:\n",
                "        json.dump(jdata, f)\n",
                "        \n",
                "    remote_data = {\"externinterfaceenabled\": True, \"deprecatedapilocalhostonly\": True, \"deprecatedapienabled\": True, \"jdanywhereapienabled\": True, \"externinterfacelocalhostonly\": False}\n",
                "    with open(os.path.join(cfg_dir, \"org.jdownloader.api.RemoteAPIConfig.json\"), \"w\") as f:\n",
                "        json.dump(remote_data, f)\n",
                "\n",
                "    print(\"\\n[*] Starting JDownloader2 in the background...\")\n",
                "    subprocess.Popen([\"java\", \"-Djava.awt.headless=true\", \"-jar\", \"JDownloader.jar\"], cwd=JD_FOLDER, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)\n",
                "    \n",
                "    print(f\"[+] JDownloader2 is Booting! Device Name: '{device_name}'\")\n",
                "    print(\"[+] You can now go to https://my.jdownloader.org, verify the device is connected, add any Premium Accounts, then run the next cell.\")\n",
                "else:\n",
                "    print(\"\\n[!] JD_EMAIL or JD_PASS not found in config. JD2 will not run. aria2c fallback will be used.\")\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"id": "process_cell"},
            "outputs": [],
            "source": [
                "# @title \ud83d\ude80 2. Processing (Download & Upload to Telegram)\n",
                "# @markdown Fill in your Source Link and Telegram Destination.\n",
                "SOURCE_LINK = \"https://torbox.app/download?id=4053953&type=torrents&name=Photoshop.2025\" # @param {type:\"string\"}\n",
                "DESTINATION = \"https://t.me/c/3974110944/2/3\" # @param {type:\"string\"}\n",
                "RETRY_FAILED = True # @param {type:\"boolean\"}\n",
                "USE_ARIA2_FALLBACK = False # @param {type:\"boolean\"}\n",
                "\n",
                "import os\n",
                "import sys\n",
                "import time\n",
                "import shutil\n",
                "import subprocess\n",
                "import asyncio\n",
                "import re\n",
                "import math\n",
                "import mimetypes\n",
                "from pathlib import Path\n",
                "import nest_asyncio\n",
                "from pyrogram import Client\n",
                "\n",
                "nest_asyncio.apply()\n",
                "\n",
                "API_ID = os.environ.get(\"API_ID\")\n",
                "API_HASH = os.environ.get(\"API_HASH\")\n",
                "SESSION_STRING = os.environ.get(\"USER_SESSION_STRING\")\n",
                "\n",
                "if not (API_ID and API_HASH and SESSION_STRING):\n",
                "    raise ValueError(\"[!] Missing Pyrogram API credentials. Did you run the setup cell?\")\n",
                "\n",
                "DL_FOLDER = \"/content/downloads\"\n",
                "JD_FOLDER = \"/content/JDownloader\"\n",
                "MAX_TG_SIZE = 4000000000 # Approx 3.9GB\n",
                "os.makedirs(DL_FOLDER, exist_ok=True)\n",
                "\n",
                "upload_stats = {\"success\": 0, \"failed\": 0, \"current\": \"\"}\n",
                "\n",
                "def get_video_duration(video_path):\n",
                "    cmd = [\"ffprobe\", \"-v\", \"error\", \"-show_entries\", \"format=duration\", \"-of\", \"default=noprint_wrappers=1:nokey=1\", video_path]\n",
                "    try:\n",
                "        return float(subprocess.check_output(cmd).decode().strip())\n",
                "    except:\n",
                "        return 0\n",
                "\n",
                "def split_file_logic(file_path):\n",
                "    size = os.path.getsize(file_path)\n",
                "    if size <= MAX_TG_SIZE:\n",
                "        return [file_path]\n",
                "    \n",
                "    parts = math.ceil(size / MAX_TG_SIZE)\n",
                "    mime = mimetypes.guess_type(file_path)[0]\n",
                "    out_files = []\n",
                "    \n",
                "    if mime and mime.startswith('video/'):\n",
                "        print(f\"\\n[*] Splitting large video (>&4GB) into {parts} parts... {file_path}\")\n",
                "        duration = get_video_duration(file_path)\n",
                "        if duration > 0:\n",
                "            part_duration = duration / parts\n",
                "            base, ext = os.path.splitext(file_path)\n",
                "            cmd = [\"ffmpeg\", \"-y\", \"-i\", file_path, \"-c\", \"copy\", \"-map\", \"0\", \"-f\", \"segment\", \"-segment_time\", str(part_duration), \"-reset_timestamps\", \"1\", f\"{base}.part%03d{ext}\"]\n",
                "            subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)\n",
                "            for i in range(parts):\n",
                "                p = f\"{base}.part{i:03d}{ext}\"\n",
                "                if os.path.exists(p):\n",
                "                    out_files.append(p)\n",
                "            if out_files:\n",
                "                os.remove(file_path)\n",
                "                return out_files\n",
                "\n",
                "    print(f\"\\n[*] Binary Splitting large file (>&4GB) into {parts} parts... {file_path}\")\n",
                "    base = file_path + \".part\"\n",
                "    cmd = [\"split\", \"--numeric-suffixes=1\", \"--suffix-length=3\", f\"--bytes={MAX_TG_SIZE}\", file_path, base]\n",
                "    subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)\n",
                "    out_files = sorted([str(p) for p in Path(os.path.dirname(file_path)).glob(os.path.basename(file_path) + \".part*\")])\n",
                "    if out_files:\n",
                "        os.remove(file_path)\n",
                "    return out_files\n",
                "\n",
                "def parse_destination(link: str):\n",
                "    match = re.search(r't\\.me/c/([^/]+)/([^/]+)', link)\n",
                "    if match:\n",
                "        return int(f\"-100{match.group(1)}\"), int(match.group(2))\n",
                "    match2 = re.search(r't\\.me/([^/]+)/([^/]+)', link)\n",
                "    if match2:\n",
                "        return match2.group(1), int(match2.group(2))\n",
                "    raise ValueError(f\"Could not parse telegram link: {link}\")\n",
                "\n",
                "async def upload_file(app: Client, file_path: str, chat_id: int, topic_id: int):\n",
                "    f_path = Path(file_path)\n",
                "    upload_stats[\"current\"] = f_path.name\n",
                "    MAX_RETRIES = 3 if RETRY_FAILED else 1\n",
                "    \n",
                "    for attempt in range(1, MAX_RETRIES + 1):\n",
                "        try:\n",
                "            def progress(current, total, filename):\n",
                "                sys.stdout.write(f\"\\r[STATUS -> ✅ : {upload_stats['success']} | ❌ : {upload_stats['failed']}] Uploading '{filename}' (Attempt {attempt}/{MAX_RETRIES}): {current * 100 / total:.1f}%\")\n",
                "                sys.stdout.flush()\n",
                "\n",
                "            await app.send_document(chat_id=chat_id, document=file_path, reply_to_message_id=topic_id, force_document=True, progress=progress, progress_args=(f_path.name,))\n",
                "            upload_stats[\"success\"] += 1\n",
                "            sys.stdout.write(f\"\\r[STATUS -> ✅ : {upload_stats['success']} | ❌ : {upload_stats['failed']}] Uploaded '{f_path.name}' successfully!                           \\n\")\n",
                "            sys.stdout.flush()\n",
                "            if os.path.exists(file_path):\n",
                "                os.remove(file_path)\n",
                "            return True\n",
                "        except Exception as e:\n",
                "            if attempt < MAX_RETRIES:\n",
                "                sys.stdout.write(f\"\\n[!] Failed to upload {f_path.name}. Retrying ({attempt}/{MAX_RETRIES}). Error: {e}\\n\")\n",
                "                await asyncio.sleep(3)\n",
                "            else:\n",
                "                upload_stats[\"failed\"] += 1\n",
                "                sys.stdout.write(f\"\\n[!] Failed to upload {f_path.name} after {MAX_RETRIES} attempts. Error: {e}\\n\")\n",
                "    return False\n",
                "\n",
                "async def uploader_task_loop(app, output_dir, chat_id, topic_id, download_process_event):\n",
                "    uploaded_files = set()\n",
                "    while not download_process_event.is_set():\n",
                "        for f in [f for f in Path(output_dir).rglob('*') if f.is_file()]:\n",
                "            path_str = str(f)\n",
                "            if f.suffix in ['.aria2', '.temp'] or path_str.endswith('.part') or path_str in uploaded_files:\n",
                "                continue\n",
                "            size1 = f.stat().st_size\n",
                "            await asyncio.sleep(2)\n",
                "            if not f.exists(): continue\n",
                "            size2 = f.stat().st_size\n",
                "            if size1 == size2 and size1 > 0:\n",
                "                uploaded_files.add(path_str)\n",
                "                split_parts = await asyncio.to_thread(split_file_logic, path_str)\n",
                "                for part in split_parts:\n",
                "                    await upload_file(app, part, chat_id, topic_id)\n",
                "                    uploaded_files.add(part)\n",
                "        await asyncio.sleep(5)\n",
                "        \n",
                "    for f in [f for f in Path(output_dir).rglob('*') if f.is_file()]:\n",
                "        path_str = str(f)\n",
                "        if f.suffix not in ['.aria2', '.temp'] and not path_str.endswith('.part') and path_str not in uploaded_files:\n",
                "            uploaded_files.add(path_str)\n",
                "            split_parts = await asyncio.to_thread(split_file_logic, path_str)\n",
                "            for part in split_parts:\n",
                "                if part not in uploaded_files:\n",
                "                    await upload_file(app, part, chat_id, topic_id)\n",
                "                    uploaded_files.add(part)\n",
                "\n",
                "async def download_task(url, output_dir, download_process_event):\n",
                "    print(f\"[*] Starting download task...\")\n",
                "    if os.environ.get(\"JD_EMAIL\") and os.environ.get(\"JD_PASS\") and not USE_ARIA2_FALLBACK:\n",
                "        if url and url.strip():\n",
                "            fw_dir = os.path.join(JD_FOLDER, \"folderwatch\")\n",
                "            os.makedirs(fw_dir, exist_ok=True)\n",
                "            with open(os.path.join(fw_dir, \"leech.crawljob\"), \"w\") as f:\n",
                "                f.write(f\"text={url}\\n\")\n",
                "                f.write(f\"downloadFolder={output_dir}\\n\")\n",
                "                f.write(\"autoStart=TRUE\\n\")\n",
                "                f.write(\"autoConfirm=TRUE\\n\")\n",
                "            print(\"\\n[*] Submitted link to JDownloader2 ! Waiting for download to stabilize...\")\n",
                "            \n",
                "        prev_size = -1\n",
                "        stagnant_count = 0\n",
                "        while True:\n",
                "            await asyncio.sleep(10)\n",
                "            size = sum(f.stat().st_size for f in Path(output_dir).rglob('*') if f.is_file() and f.suffix not in ['.part', '.aria2'])\n",
                "            if size == prev_size and size > 0:\n",
                "                stagnant_count += 1\n",
                "            else:\n",
                "                stagnant_count = 0\n",
                "            prev_size = size\n",
                "            threshold = 10 if size > 0 else 60\n",
                "            if stagnant_count > threshold:\n",
                "                break\n",
                "    else:\n",
                "        if url and url.strip():\n",
                "            process = await asyncio.create_subprocess_exec(\"aria2c\", \"--console-log-level=warn\", \"--max-connection-per-server=8\", \"--split=8\", \"--dir\", output_dir, url)\n",
                "            await process.communicate()\n",
                "        \n",
                "    print(\"\\n[*] Download Stream Concluded!\")\n",
                "    download_process_event.set()\n",
                "\n",
                "async def main():\n",
                "    if os.path.exists(DL_FOLDER):\n",
                "        shutil.rmtree(DL_FOLDER)\n",
                "    os.makedirs(DL_FOLDER, exist_ok=True)\n",
                "    \n",
                "    chat_id, topic_id = parse_destination(DESTINATION)\n",
                "    print(f\"[*] Parsed Destination: Chat: {chat_id}, Topic/ReplyTo: {topic_id}\")\n",
                "    print(\"[*] Authenticating with Telegram...\")\n",
                "    \n",
                "    app = Client(\"colab_session\", api_id=int(API_ID), api_hash=API_HASH, session_string=SESSION_STRING)\n",
                "    await app.start()\n",
                "    \n",
                "    start_time = time.time()\n",
                "    download_event = asyncio.Event()\n",
                "    \n",
                "    dl_task = asyncio.create_task(download_task(SOURCE_LINK, DL_FOLDER, download_event))\n",
                "    up_task = asyncio.create_task(uploader_task_loop(app, DL_FOLDER, chat_id, topic_id, download_event))\n",
                "    \n",
                "    await asyncio.gather(dl_task, up_task)\n",
                "    await app.stop()\n",
                "    \n",
                "    print(f\"\\n[+] All processes completed in {time.time() - start_time:.2f} seconds.\")\n",
                "    print(f\"[+] Final Statistics -> ✅ Successful: {upload_stats['success']} | \u274c Failed: {upload_stats['failed']}\")\n",
                "    print(\"[+] Colab runtime is clear of the uploaded files.\")\n",
                "\n",
                "loop = asyncio.get_event_loop()\n",
                "loop.run_until_complete(main())\n"
            ]
        }
    ],
    "metadata": {
        "colab": {"provenance": []},
        "kernelspec": {"display_name": "Python 3", "name": "python3"},
        "language_info": {"name": "python"}
    },
    "nbformat": 4,
    "nbformat_minor": 0
}

with open('/workspaces/exportclonetgbot/JDownloader2_Leecher.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)
